@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar
POST {{endpoint}} HTTP/1.1
content-type: application/json
x-api-key: blahblah

{ "make" : "lada", "model" : "2101", "year" : 1980 }
###

@newCar = {{postACar.response.body._id}}
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json
x-api-key: blahblah
###
GET  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json
x-api-key: blahblah

###

DELETE  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

###
GET http://localhost:3000/api/v1/cars HTTP/1.1
content-type: application/json
x-api-key: blahblah
